-- MySQL Script generated by MySQL Workbench
-- 01/02/16 11:56:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TypeMembre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TypeMembre` (
  `idTypeMembre` INT NOT NULL COMMENT '',
  `libelleTypeMembre` VARCHAR(45) NULL COMMENT '',
  `description` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idTypeMembre`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Region` (
  `codeRegion` VARCHAR(10) NOT NULL COMMENT '',
  `region` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`codeRegion`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Membre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Membre` (
  `codeMembre` VARCHAR(50) NOT NULL COMMENT '',
  `nomMembre` VARCHAR(45) NULL COMMENT '',
  `prenomMembre` VARCHAR(45) NULL COMMENT '',
  `dateNaiss` VARCHAR(45) NULL COMMENT '',
  `lieuNaiss` VARCHAR(45) NULL COMMENT '',
  `codeRegion` VARCHAR(10) NOT NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `adress1` VARCHAR(45) NULL COMMENT '',
  `adress2` VARCHAR(45) NULL COMMENT '',
  `numTel1` VARCHAR(45) NULL COMMENT '',
  `numTel2` VARCHAR(45) NULL COMMENT '',
  `etatCompte` VARCHAR(45) NULL COMMENT 'L’etat du compte d’utilisateur activé=1 par défunt c’est désactivé=0\n',
  `userId` VARCHAR(45) NULL COMMENT '',
  `mdp` VARCHAR(45) NULL COMMENT '',
  `idTypeMembre` INT NOT NULL COMMENT '',
  `etat` VARCHAR(45) NULL COMMENT 'Actif\nInactif\n',
  `anneeBac` INT NULL COMMENT '',
  PRIMARY KEY (`codeMembre`)  COMMENT '',
  INDEX `fk_Membre_TypeMembre1_idx` (`idTypeMembre` ASC)  COMMENT '',
  INDEX `fk_Membre_Region1_idx` (`codeRegion` ASC)  COMMENT '',
  CONSTRAINT `fk_Membre_TypeMembre1`
    FOREIGN KEY (`idTypeMembre`)
    REFERENCES `mydb`.`TypeMembre` (`idTypeMembre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Membre_Region1`
    FOREIGN KEY (`codeRegion`)
    REFERENCES `mydb`.`Region` (`codeRegion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TypeEntite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TypeEntite` (
  `idTypeEntite` INT NOT NULL COMMENT '',
  `libelleTypeEntite` VARCHAR(45) NULL COMMENT '',
  `description` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idTypeEntite`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entite` (
  `idEntite` VARCHAR(45) NOT NULL COMMENT '',
  `idEntiteParent` VARCHAR(45) NULL COMMENT '',
  `libelleEntite` VARCHAR(45) NULL COMMENT '',
  `idTypeEntite` INT NOT NULL COMMENT '',
  `codeRegion` VARCHAR(10) NULL COMMENT '',
  PRIMARY KEY (`idEntite`)  COMMENT '',
  INDEX `fk_Entite_Entite1_idx` (`idEntiteParent` ASC)  COMMENT '',
  INDEX `fk_Entite_TypeEntite1_idx` (`idTypeEntite` ASC)  COMMENT '',
  INDEX `fk_Entite_Region1_idx` (`codeRegion` ASC)  COMMENT '',
  CONSTRAINT `fk_Entite_Entite1`
    FOREIGN KEY (`idEntiteParent`)
    REFERENCES `mydb`.`Entite` (`idEntite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entite_TypeEntite1`
    FOREIGN KEY (`idTypeEntite`)
    REFERENCES `mydb`.`TypeEntite` (`idTypeEntite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entite_Region1`
    FOREIGN KEY (`codeRegion`)
    REFERENCES `mydb`.`Region` (`codeRegion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exercice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Exercice` (
  `codeExercice` INT NOT NULL COMMENT '',
  `libelleExercice` VARCHAR(45) NULL COMMENT '',
  `enCours` INT NULL COMMENT '',
  PRIMARY KEY (`codeExercice`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evenement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evenement` (
  `idEvenement` INT NOT NULL COMMENT '',
  `libelleEvenement` VARCHAR(45) NULL COMMENT '',
  `dateEvenement` VARCHAR(45) NULL COMMENT '',
  `lieuEvenement` VARCHAR(45) NULL COMMENT '',
  `idEntite` VARCHAR(45) NOT NULL COMMENT '',
  `codeExercice` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idEvenement`)  COMMENT '',
  INDEX `fk_Evenement_Entite1_idx` (`idEntite` ASC)  COMMENT '',
  INDEX `fk_Evenement_Exercice1_idx` (`codeExercice` ASC)  COMMENT '',
  CONSTRAINT `fk_Evenement_Entite1`
    FOREIGN KEY (`idEntite`)
    REFERENCES `mydb`.`Entite` (`idEntite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evenement_Exercice1`
    FOREIGN KEY (`codeExercice`)
    REFERENCES `mydb`.`Exercice` (`codeExercice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TypeCotisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TypeCotisation` (
  `idTypeCotisation` INT NOT NULL COMMENT '',
  `libelleTypeCotisation` VARCHAR(45) NULL COMMENT 'Mensuelle \nEvénementielle\n',
  PRIMARY KEY (`idTypeCotisation`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mois`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mois` (
  `mois` INT NOT NULL COMMENT '',
  `annee` INT NOT NULL COMMENT '',
  PRIMARY KEY (`mois`, `annee`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cotisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cotisation` (
  `idCotisation` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codeMembre` VARCHAR(50) NOT NULL COMMENT '',
  `dateCotisation` VARCHAR(45) NULL COMMENT '',
  `montant` INT NULL COMMENT '',
  `idTypeCotisation` INT NOT NULL COMMENT 'Mensuelle\nEvenementielle\n',
  `idEvenement` INT NULL COMMENT '',
  `mois` INT NULL COMMENT '',
  `annee` INT NULL COMMENT '',
  PRIMARY KEY (`idCotisation`)  COMMENT '',
  INDEX `fk_Cotisation_Evenement1_idx` (`idEvenement` ASC)  COMMENT '',
  INDEX `fk_Cotisation_TypeCotisation1_idx` (`idTypeCotisation` ASC)  COMMENT '',
  INDEX `fk_Cotisation_Mois1_idx` (`mois` ASC, `annee` ASC)  COMMENT '',
  INDEX `fk_Cotisation_Membre1_idx` (`codeMembre` ASC)  COMMENT '',
  CONSTRAINT `fk_Cotisation_Evenement1`
    FOREIGN KEY (`idEvenement`)
    REFERENCES `mydb`.`Evenement` (`idEvenement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cotisation_TypeCotisation1`
    FOREIGN KEY (`idTypeCotisation`)
    REFERENCES `mydb`.`TypeCotisation` (`idTypeCotisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cotisation_Mois1`
    FOREIGN KEY (`mois` , `annee`)
    REFERENCES `mydb`.`Mois` (`mois` , `annee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cotisation_Membre1`
    FOREIGN KEY (`codeMembre`)
    REFERENCES `mydb`.`Membre` (`codeMembre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appartenance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Appartenance` (
  `codeMembre` VARCHAR(50) NOT NULL COMMENT '',
  `idEntite` VARCHAR(45) NOT NULL COMMENT '',
  `Role` VARCHAR(45) NULL COMMENT '',
  `codeExercice` INT NOT NULL COMMENT '',
  `dateAdhesion` VARCHAR(45) NULL COMMENT '',
  `typeAdhesion` VARCHAR(45) NULL COMMENT 'Nouvelle Adhésion\nRenouvellement\n',
  `niveau` VARCHAR(45) NULL COMMENT 'A renseigner si typemembre = étudiant',
  `fonction` VARCHAR(45) NULL COMMENT 'A renseigner si typemembre = travailleur \n',
  PRIMARY KEY (`codeMembre`, `idEntite`)  COMMENT '',
  INDEX `fk_Appartenance_Entite1_idx` (`idEntite` ASC)  COMMENT '',
  INDEX `fk_Appartenance_Exercice1_idx` (`codeExercice` ASC)  COMMENT '',
  CONSTRAINT `fk_Appartenance_Membre1`
    FOREIGN KEY (`codeMembre`)
    REFERENCES `mydb`.`Membre` (`codeMembre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appartenance_Entite1`
    FOREIGN KEY (`idEntite`)
    REFERENCES `mydb`.`Entite` (`idEntite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appartenance_Exercice1`
    FOREIGN KEY (`codeExercice`)
    REFERENCES `mydb`.`Exercice` (`codeExercice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Responsabilite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Responsabilite` (
  `idResponsabilite` INT NOT NULL COMMENT '',
  `codeMembre` VARCHAR(50) NOT NULL COMMENT '',
  `idEntite` VARCHAR(45) NOT NULL COMMENT '',
  `codeExercice` INT NOT NULL COMMENT '',
  `TitreResponsabilite` VARCHAR(45) NOT NULL COMMENT '',
  `dateDeb` INT NOT NULL COMMENT '',
  `dateFin` INT NULL COMMENT '',
  `observation` VARCHAR(255) NULL COMMENT '',
  INDEX `fk_Responsabilite_Membre1_idx` (`codeMembre` ASC)  COMMENT '',
  INDEX `fk_Responsabilite_Entite1_idx` (`idEntite` ASC)  COMMENT '',
  INDEX `fk_Responsabilite_Exercice1_idx` (`codeExercice` ASC)  COMMENT '',
  PRIMARY KEY (`idResponsabilite`)  COMMENT '',
  CONSTRAINT `fk_Responsabilite_Membre1`
    FOREIGN KEY (`codeMembre`)
    REFERENCES `mydb`.`Membre` (`codeMembre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Responsabilite_Entite1`
    FOREIGN KEY (`idEntite`)
    REFERENCES `mydb`.`Entite` (`idEntite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Responsabilite_Exercice1`
    FOREIGN KEY (`codeExercice`)
    REFERENCES `mydb`.`Exercice` (`codeExercice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TypeEtab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TypeEtab` (
  `idTypeEtab` INT NOT NULL COMMENT '',
  `typeEtab` VARCHAR(45) NULL COMMENT '',
  `description` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idTypeEtab`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Etablissement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Etablissement` (
  `idEtablissement` INT NOT NULL COMMENT '',
  `etablissement` VARCHAR(45) NULL COMMENT '',
  `description` VARCHAR(45) NULL COMMENT '',
  `idTypeEtab` INT NOT NULL COMMENT '',
  `idEtablissementParent` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idEtablissement`, `idEtablissementParent`)  COMMENT '',
  INDEX `fk_Etablissement_TypeEtab1_idx` (`idTypeEtab` ASC)  COMMENT '',
  INDEX `fk_Etablissement_Etablissement1_idx` (`idEtablissementParent` ASC)  COMMENT '',
  CONSTRAINT `fk_Etablissement_TypeEtab1`
    FOREIGN KEY (`idTypeEtab`)
    REFERENCES `mydb`.`TypeEtab` (`idTypeEtab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Etablissement_Etablissement1`
    FOREIGN KEY (`idEtablissementParent`)
    REFERENCES `mydb`.`Etablissement` (`idEtablissement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Domaine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Domaine` (
  `idDomaine` INT NOT NULL COMMENT '',
  `codeDomaine` VARCHAR(45) NULL COMMENT '',
  `libelleDomaine` VARCHAR(45) NULL COMMENT '',
  `description` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idDomaine`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AppartEtab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AppartEtab` (
  `idAppartEtab` INT NOT NULL COMMENT '',
  `dateAppart` VARCHAR(45) NULL COMMENT '',
  `dateFin` VARCHAR(45) NULL COMMENT '',
  `idEtablissement` INT NOT NULL COMMENT '',
  `codeMembre` VARCHAR(50) NOT NULL COMMENT '',
  `idDomaine` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idAppartEtab`, `idEtablissement`, `codeMembre`, `idDomaine`)  COMMENT '',
  INDEX `fk_AppartEtab_Etablissement1_idx` (`idEtablissement` ASC)  COMMENT '',
  INDEX `fk_AppartEtab_Membre1_idx` (`codeMembre` ASC)  COMMENT '',
  INDEX `fk_AppartEtab_Domaine1_idx` (`idDomaine` ASC)  COMMENT '',
  CONSTRAINT `fk_AppartEtab_Etablissement1`
    FOREIGN KEY (`idEtablissement`)
    REFERENCES `mydb`.`Etablissement` (`idEtablissement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AppartEtab_Membre1`
    FOREIGN KEY (`codeMembre`)
    REFERENCES `mydb`.`Membre` (`codeMembre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AppartEtab_Domaine1`
    FOREIGN KEY (`idDomaine`)
    REFERENCES `mydb`.`Domaine` (`idDomaine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
